OUTPUT_FOLDER_PATH = "out"

TRACK_FOLDER_PATH = "track"
TRACK_PATH = f"{TRACK_FOLDER_PATH}/track.npy"

ATTEMPTS_PATH = f"{OUTPUT_FOLDER_PATH}/attempts"
LEARNING_CURVE_PATH = f"{OUTPUT_FOLDER_PATH}/learning_curve.png"
BEST_ATTEMPT_PATH = f"{OUTPUT_FOLDER_PATH}/best_attempt.mp4"
COMBINED_ATTEMPTS_PATH = f"{OUTPUT_FOLDER_PATH}/combined_attempts.mp4"
Q_TABLE_PATH = f"{OUTPUT_FOLDER_PATH}/q_table.npy"